filebeat.modules:
#- module: system
  #syslog:
  #  enabled: true
  #auth:
  #  enabled: true
#- module: auditd
  #log:
    # - Does not look like Auditd is supported in Alpine linux: https://github.com/linuxkit/linuxkit/issues/52
    # - CentOS does not need us to install the audit system, it ships as standard. If you are using Ubuntu, though,
    # this is probably something you would want to install. (sudo apt-get install -y auditd audispd-plugins)
  #  enabled: true
- module: cef
  log:
    enabled: true
    var:
      syslog_host: ${BINDING_IP}
      syslog_port: ${CEF_PORT}

#============================= Innputs =======================================

filebeat.inputs:
    ### NETFLOW ###
  - type: netflow
    max_message_size: 10KiB
    host: "${BINDING_IP}:${NF_PORT}"
    protocols: [ v5, v9, ipfix ]
    expiration_timeout: 30m
    queue_size: 8192
    #index: "%{[agent.name]}-netflow-%{+yyyy.MM.dd}"
    #pipeline: geoip-info
    
    ### SYSLOG ###
  - type: syslog
    format: rfc3164
    var.convert_timezone: false
    protocol.udp:
      host: "${BINDING_IP}:${SYSLOG_PORT}"
    index: "syslog-%{[agent.name]}-%{+yyyy.MM.dd}"
    #pipeline: mikrotik-parser

#================================ Processors ===================================
processors:
- add_cloud_metadata: ~
- add_docker_metadata: ~
- add_locale:
    format: offset
- add_host_metadata:
    netinfo.enabled: true
- dns:
    type: reverse
    action: append
    fields:
      source.ip: source.domain
      destination.ip: destination.domain
      #server.ip: server.domain
      #client.ip: client.domain
    nameservers: ['8.8.8.8', '192.168.88.1']
    timeout: 500ms
    tag_on_failure: [_dns_reverse_lookup_failed]

#========================== Elasticsearch output ===============================
output.elasticsearch:
  hosts: ["192.168.30.2:9200"]
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  pipeline: geoip-info


#============================== Dashboards =====================================
# setup.dashboards:
#   enabled: true

#============================== Kibana =========================================
setup.kibana:
  host: "${KIBANA_HOST}"
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}

#============================== Xpack Monitoring ===============================
xpack.monitoring:
  enabled: true
  elasticsearch:

